/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author User
 */
public class UserWithdraw extends javax.swing.JPanel {

    /**
     * Creates new form UserWithdraw
     */
    public UserWithdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpNavbar = new javax.swing.JPanel();
        btnUserDashboard = new javax.swing.JButton();
        btnUserDeposit = new javax.swing.JButton();
        btnUserAcc = new javax.swing.JButton();
        btnUserWithdraw = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserTransferFunds = new javax.swing.JButton();
        btnUserBillsPayment = new javax.swing.JButton();
        btnUserCardService = new javax.swing.JButton();
        btnUserSecuritySettings = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jUserEnterAmount2 = new javax.swing.JTextField();
        btnUser3 = new javax.swing.JButton();
        btnUser5 = new javax.swing.JButton();
        btnUser6 = new javax.swing.JButton();
        btnUser7 = new javax.swing.JButton();
        btnUser2 = new javax.swing.JButton();
        btnUser4 = new javax.swing.JButton();
        btnUser9 = new javax.swing.JButton();
        btnUser8 = new javax.swing.JButton();
        btnUser1 = new javax.swing.JButton();
        btnUser0 = new javax.swing.JButton();
        btnUserClear = new javax.swing.JButton();
        btnUserBackArrow = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jUserWithdraw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER DASHBOARD");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, -1));

        jpNavbar.setBackground(new java.awt.Color(3, 45, 53));

        btnUserDashboard.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDashboard.setText("Dashboard");
        btnUserDashboard.setToolTipText("");
        btnUserDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDashboardActionPerformed(evt);
            }
        });

        btnUserDeposit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDeposit.setText("Deposit");
        btnUserDeposit.setToolTipText("");
        btnUserDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDepositActionPerformed(evt);
            }
        });

        btnUserAcc.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserAcc.setText("My Account");
        btnUserAcc.setToolTipText("");
        btnUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccActionPerformed(evt);
            }
        });

        btnUserWithdraw.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserWithdraw.setText("Withdraw");
        btnUserWithdraw.setToolTipText("");
        btnUserWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserTransferFunds.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserTransferFunds.setText("Transfer Funds");
        btnUserTransferFunds.setToolTipText("");
        btnUserTransferFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserTransferFundsActionPerformed(evt);
            }
        });

        btnUserBillsPayment.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserBillsPayment.setText("Bills Payment");
        btnUserBillsPayment.setToolTipText("");
        btnUserBillsPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserBillsPaymentActionPerformed(evt);
            }
        });

        btnUserCardService.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserCardService.setText("Card Service");
        btnUserCardService.setToolTipText("");
        btnUserCardService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserCardServiceActionPerformed(evt);
            }
        });

        btnUserSecuritySettings.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserSecuritySettings.setText("Security Settings");
        btnUserSecuritySettings.setToolTipText("");
        btnUserSecuritySettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSecuritySettingsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USER");

        javax.swing.GroupLayout jpNavbarLayout = new javax.swing.GroupLayout(jpNavbar);
        jpNavbar.setLayout(jpNavbarLayout);
        jpNavbarLayout.setHorizontalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUserWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserTransferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserBillsPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserCardService, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserSecuritySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNavbarLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(73, 73, 73)))
        );
        jpNavbarLayout.setVerticalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnUserDashboard)
                .addGap(30, 30, 30)
                .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUserDeposit)
                .addGap(30, 30, 30)
                .addComponent(btnUserWithdraw)
                .addGap(28, 28, 28)
                .addComponent(btnUserTransferFunds)
                .addGap(29, 29, 29)
                .addComponent(btnUserBillsPayment)
                .addGap(28, 28, 28)
                .addComponent(btnUserCardService)
                .addGap(27, 27, 27)
                .addComponent(btnUserSecuritySettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpNavbarLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel6)
                    .addContainerGap(670, Short.MAX_VALUE)))
        );

        add(jpNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 740));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("Withdraw");

        jUserEnterAmount2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jUserEnterAmount2.setText("Enter Amount: ");

        btnUser3.setBackground(new java.awt.Color(0, 153, 153));
        btnUser3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser3.setForeground(new java.awt.Color(255, 255, 255));
        btnUser3.setText("3");

        btnUser5.setBackground(new java.awt.Color(0, 153, 153));
        btnUser5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser5.setForeground(new java.awt.Color(255, 255, 255));
        btnUser5.setText("5");

        btnUser6.setBackground(new java.awt.Color(0, 153, 153));
        btnUser6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser6.setForeground(new java.awt.Color(255, 255, 255));
        btnUser6.setText("6");

        btnUser7.setBackground(new java.awt.Color(0, 153, 153));
        btnUser7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser7.setForeground(new java.awt.Color(255, 255, 255));
        btnUser7.setText("7");

        btnUser2.setBackground(new java.awt.Color(0, 153, 153));
        btnUser2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser2.setForeground(new java.awt.Color(255, 255, 255));
        btnUser2.setText("2");

        btnUser4.setBackground(new java.awt.Color(0, 153, 153));
        btnUser4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser4.setForeground(new java.awt.Color(255, 255, 255));
        btnUser4.setText("4");

        btnUser9.setBackground(new java.awt.Color(0, 153, 153));
        btnUser9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser9.setForeground(new java.awt.Color(255, 255, 255));
        btnUser9.setText("9");

        btnUser8.setBackground(new java.awt.Color(0, 153, 153));
        btnUser8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser8.setForeground(new java.awt.Color(255, 255, 255));
        btnUser8.setText("8");

        btnUser1.setBackground(new java.awt.Color(0, 153, 153));
        btnUser1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser1.setForeground(new java.awt.Color(255, 255, 255));
        btnUser1.setText("1");

        btnUser0.setBackground(new java.awt.Color(0, 153, 153));
        btnUser0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUser0.setForeground(new java.awt.Color(255, 255, 255));
        btnUser0.setText("0");

        btnUserClear.setBackground(new java.awt.Color(0, 153, 153));
        btnUserClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUserClear.setForeground(new java.awt.Color(255, 255, 255));
        btnUserClear.setText("Clear");

        btnUserBackArrow.setBackground(new java.awt.Color(0, 153, 153));
        btnUserBackArrow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUserBackArrow.setForeground(new java.awt.Color(255, 255, 255));
        btnUserBackArrow.setText("<-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jUserEnterAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUser0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUserClear)
                                .addGap(12, 12, 12)
                                .addComponent(btnUserBackArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnUser4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnUser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnUser9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 86, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUserEnterAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserBackArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 320, 480));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Current Balance:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("Reserve After Withdrawal:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 440, 200));

        jUserWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jUserWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/money (2).png"))); // NOI18N
        jUserWithdraw.setText("Withdraw");
        jUserWithdraw.setToolTipText("");
        add(jUserWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/user.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDashboardActionPerformed

    private void btnUserDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDepositActionPerformed

    private void btnUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserAccActionPerformed

    private void btnUserWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserTransferFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserTransferFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserTransferFundsActionPerformed

    private void btnUserBillsPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserBillsPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserBillsPaymentActionPerformed

    private void btnUserCardServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCardServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserCardServiceActionPerformed

    private void btnUserSecuritySettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSecuritySettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserSecuritySettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUser0;
    private javax.swing.JButton btnUser1;
    private javax.swing.JButton btnUser2;
    private javax.swing.JButton btnUser3;
    private javax.swing.JButton btnUser4;
    private javax.swing.JButton btnUser5;
    private javax.swing.JButton btnUser6;
    private javax.swing.JButton btnUser7;
    private javax.swing.JButton btnUser8;
    private javax.swing.JButton btnUser9;
    private javax.swing.JButton btnUserAcc;
    private javax.swing.JButton btnUserBackArrow;
    private javax.swing.JButton btnUserBillsPayment;
    private javax.swing.JButton btnUserCardService;
    private javax.swing.JButton btnUserClear;
    private javax.swing.JButton btnUserDashboard;
    private javax.swing.JButton btnUserDeposit;
    private javax.swing.JButton btnUserSecuritySettings;
    private javax.swing.JButton btnUserTransferFunds;
    private javax.swing.JButton btnUserWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jUserEnterAmount2;
    private javax.swing.JButton jUserWithdraw;
    private javax.swing.JPanel jpNavbar;
    // End of variables declaration//GEN-END:variables
}
