/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author User
 */
public class UserDashboard extends javax.swing.JPanel {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpNavbar = new javax.swing.JPanel();
        btnUserDashboard = new javax.swing.JButton();
        btnUserDeposit = new javax.swing.JButton();
        btnUserAcc = new javax.swing.JButton();
        btnUserWithdraw = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserTransferFunds = new javax.swing.JButton();
        btnUserBillsPayment = new javax.swing.JButton();
        btnUserCardService = new javax.swing.JButton();
        btnUserSecuritySettings = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jpUserApplicationContainer3 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication9 = new javax.swing.JLabel();
        javax.swing.JLabel txtUserApplication10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpUserApplicationContainer4 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication13 = new javax.swing.JLabel();
        jUserFullStatement = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUserTransactionHistoryTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jUserMiniStatement = new javax.swing.JButton();
        jpUserApplicationContainer5 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication16 = new javax.swing.JLabel();
        jUserTransferFunds = new javax.swing.JButton();
        jUserWithdraw = new javax.swing.JButton();
        jUserDeposit = new javax.swing.JButton();
        jUserPayBills = new javax.swing.JButton();
        jpUserApplicationContainer6 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication11 = new javax.swing.JLabel();
        javax.swing.JLabel txtUserApplication18 = new javax.swing.JLabel();
        jUserViewAll = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpUserApplicationContainer7 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication19 = new javax.swing.JLabel();
        javax.swing.JLabel txtUserApplication20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jpUserApplicationContainer8 = new javax.swing.JPanel();
        javax.swing.JLabel txtUserApplication22 = new javax.swing.JLabel();
        javax.swing.JLabel txtUserApplication23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpNavbar.setBackground(new java.awt.Color(3, 45, 53));

        btnUserDashboard.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDashboard.setText("Dashboard");
        btnUserDashboard.setToolTipText("");
        btnUserDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDashboardActionPerformed(evt);
            }
        });

        btnUserDeposit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDeposit.setText("Deposit");
        btnUserDeposit.setToolTipText("");
        btnUserDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDepositActionPerformed(evt);
            }
        });

        btnUserAcc.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserAcc.setText("My Account");
        btnUserAcc.setToolTipText("");
        btnUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccActionPerformed(evt);
            }
        });

        btnUserWithdraw.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserWithdraw.setText("Withdraw");
        btnUserWithdraw.setToolTipText("");
        btnUserWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserTransferFunds.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserTransferFunds.setText("Transfer Funds");
        btnUserTransferFunds.setToolTipText("");
        btnUserTransferFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserTransferFundsActionPerformed(evt);
            }
        });

        btnUserBillsPayment.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserBillsPayment.setText("Bills Payment");
        btnUserBillsPayment.setToolTipText("");
        btnUserBillsPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserBillsPaymentActionPerformed(evt);
            }
        });

        btnUserCardService.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserCardService.setText("Card Service");
        btnUserCardService.setToolTipText("");
        btnUserCardService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserCardServiceActionPerformed(evt);
            }
        });

        btnUserSecuritySettings.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserSecuritySettings.setText("Security Settings");
        btnUserSecuritySettings.setToolTipText("");
        btnUserSecuritySettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSecuritySettingsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER");

        javax.swing.GroupLayout jpNavbarLayout = new javax.swing.GroupLayout(jpNavbar);
        jpNavbar.setLayout(jpNavbarLayout);
        jpNavbarLayout.setHorizontalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUserWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserTransferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserBillsPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserCardService, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserSecuritySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNavbarLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(73, 73, 73)))
        );
        jpNavbarLayout.setVerticalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnUserDashboard)
                .addGap(30, 30, 30)
                .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUserDeposit)
                .addGap(30, 30, 30)
                .addComponent(btnUserWithdraw)
                .addGap(28, 28, 28)
                .addComponent(btnUserTransferFunds)
                .addGap(29, 29, 29)
                .addComponent(btnUserBillsPayment)
                .addGap(28, 28, 28)
                .addComponent(btnUserCardService)
                .addGap(27, 27, 27)
                .addComponent(btnUserSecuritySettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpNavbarLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel5)
                    .addContainerGap(670, Short.MAX_VALUE)))
        );

        jPanel1.add(jpNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 740));

        jpUserApplicationContainer3.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication9.setText("Summary");

        txtUserApplication10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication10.setText("Account");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Current Balance - ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Account Number - ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Account Type -");

        javax.swing.GroupLayout jpUserApplicationContainer3Layout = new javax.swing.GroupLayout(jpUserApplicationContainer3);
        jpUserApplicationContainer3.setLayout(jpUserApplicationContainer3Layout);
        jpUserApplicationContainer3Layout.setHorizontalGroup(
            jpUserApplicationContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpUserApplicationContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserApplication10)
                    .addComponent(txtUserApplication9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpUserApplicationContainer3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpUserApplicationContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jpUserApplicationContainer3Layout.setVerticalGroup(
            jpUserApplicationContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserApplication10)
                .addGap(2, 2, 2)
                .addComponent(txtUserApplication9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jpUserApplicationContainer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 200, 190));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 373, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER DASHBOARD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jpUserApplicationContainer4.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication13.setText("Transaction History");

        jUserFullStatement.setText("Full Statement");

        jUserTransactionHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Type", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jUserTransactionHistoryTable);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Full Statement");

        jUserMiniStatement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jUserMiniStatement.setText("Mini Statement");

        javax.swing.GroupLayout jpUserApplicationContainer4Layout = new javax.swing.GroupLayout(jpUserApplicationContainer4);
        jpUserApplicationContainer4.setLayout(jpUserApplicationContainer4Layout);
        jpUserApplicationContainer4Layout.setHorizontalGroup(
            jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserApplication13)
                    .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                        .addGroup(jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jUserMiniStatement)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jUserFullStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpUserApplicationContainer4Layout.setVerticalGroup(
            jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtUserApplication13)
                .addGroup(jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jUserFullStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jpUserApplicationContainer4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpUserApplicationContainer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jUserMiniStatement))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jpUserApplicationContainer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 380, 250));

        jpUserApplicationContainer5.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication16.setText("Quick Actions");

        jUserTransferFunds.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jUserTransferFunds.setText("Transfer Funds");

        jUserWithdraw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jUserWithdraw.setText("Withdraw");

        jUserDeposit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jUserDeposit.setText("Deposit");

        jUserPayBills.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jUserPayBills.setText("Pay Bills");

        javax.swing.GroupLayout jpUserApplicationContainer5Layout = new javax.swing.GroupLayout(jpUserApplicationContainer5);
        jpUserApplicationContainer5.setLayout(jpUserApplicationContainer5Layout);
        jpUserApplicationContainer5Layout.setHorizontalGroup(
            jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserApplication16)
                    .addGroup(jpUserApplicationContainer5Layout.createSequentialGroup()
                        .addGroup(jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUserWithdraw)
                            .addComponent(jUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGap(32, 32, 32)
                .addGroup(jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserPayBills)
                    .addComponent(jUserTransferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jpUserApplicationContainer5Layout.setVerticalGroup(
            jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtUserApplication16)
                .addGap(35, 35, 35)
                .addGroup(jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserTransferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jpUserApplicationContainer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserPayBills, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel1.add(jpUserApplicationContainer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        jpUserApplicationContainer6.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication11.setText("Transactions");

        txtUserApplication18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication18.setText("Recent");

        jUserViewAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jUserViewAll.setText("View All");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Today:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Yesterday:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Nov. 25 -");

        javax.swing.GroupLayout jpUserApplicationContainer6Layout = new javax.swing.GroupLayout(jpUserApplicationContainer6);
        jpUserApplicationContainer6.setLayout(jpUserApplicationContainer6Layout);
        jpUserApplicationContainer6Layout.setHorizontalGroup(
            jpUserApplicationContainer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpUserApplicationContainer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserApplication18)
                    .addComponent(txtUserApplication11)
                    .addGroup(jpUserApplicationContainer6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpUserApplicationContainer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jUserViewAll))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpUserApplicationContainer6Layout.setVerticalGroup(
            jpUserApplicationContainer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserApplication18)
                .addGap(2, 2, 2)
                .addComponent(txtUserApplication11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserViewAll)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jpUserApplicationContainer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 190));

        jpUserApplicationContainer7.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication19.setText("Reminders");

        txtUserApplication20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication20.setText("Bills &");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Electric Bill - Due:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Water Bill - Due:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Internet Bill - Due:");

        javax.swing.GroupLayout jpUserApplicationContainer7Layout = new javax.swing.GroupLayout(jpUserApplicationContainer7);
        jpUserApplicationContainer7.setLayout(jpUserApplicationContainer7Layout);
        jpUserApplicationContainer7Layout.setHorizontalGroup(
            jpUserApplicationContainer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpUserApplicationContainer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserApplication19)
                    .addComponent(txtUserApplication20)
                    .addGroup(jpUserApplicationContainer7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpUserApplicationContainer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jpUserApplicationContainer7Layout.setVerticalGroup(
            jpUserApplicationContainer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserApplication20)
                .addGap(2, 2, 2)
                .addComponent(txtUserApplication19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jpUserApplicationContainer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        jpUserApplicationContainer8.setBackground(new java.awt.Color(221, 221, 221));

        txtUserApplication22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication22.setText("3 New");

        txtUserApplication23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUserApplication23.setText("Notifications");

        javax.swing.GroupLayout jpUserApplicationContainer8Layout = new javax.swing.GroupLayout(jpUserApplicationContainer8);
        jpUserApplicationContainer8.setLayout(jpUserApplicationContainer8Layout);
        jpUserApplicationContainer8Layout.setHorizontalGroup(
            jpUserApplicationContainer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUserApplicationContainer8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpUserApplicationContainer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserApplication23)
                    .addGroup(jpUserApplicationContainer8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtUserApplication22)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpUserApplicationContainer8Layout.setVerticalGroup(
            jpUserApplicationContainer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpUserApplicationContainer8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserApplication23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(txtUserApplication22)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jpUserApplicationContainer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/user.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDashboardActionPerformed

    private void btnUserDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDepositActionPerformed

    private void btnUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserAccActionPerformed

    private void btnUserWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserTransferFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserTransferFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserTransferFundsActionPerformed

    private void btnUserBillsPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserBillsPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserBillsPaymentActionPerformed

    private void btnUserCardServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCardServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserCardServiceActionPerformed

    private void btnUserSecuritySettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSecuritySettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserSecuritySettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserAcc;
    private javax.swing.JButton btnUserBillsPayment;
    private javax.swing.JButton btnUserCardService;
    private javax.swing.JButton btnUserDashboard;
    private javax.swing.JButton btnUserDeposit;
    private javax.swing.JButton btnUserSecuritySettings;
    private javax.swing.JButton btnUserTransferFunds;
    private javax.swing.JButton btnUserWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jUserDeposit;
    private javax.swing.JButton jUserFullStatement;
    private javax.swing.JButton jUserMiniStatement;
    private javax.swing.JButton jUserPayBills;
    private javax.swing.JTable jUserTransactionHistoryTable;
    private javax.swing.JButton jUserTransferFunds;
    private javax.swing.JButton jUserViewAll;
    private javax.swing.JButton jUserWithdraw;
    private javax.swing.JPanel jpNavbar;
    private javax.swing.JPanel jpUserApplicationContainer3;
    private javax.swing.JPanel jpUserApplicationContainer4;
    private javax.swing.JPanel jpUserApplicationContainer5;
    private javax.swing.JPanel jpUserApplicationContainer6;
    private javax.swing.JPanel jpUserApplicationContainer7;
    private javax.swing.JPanel jpUserApplicationContainer8;
    // End of variables declaration//GEN-END:variables
}
