/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author User
 */
public class UserDeposit extends javax.swing.JPanel {

    /**
     * Creates new form UserDeposit
     */
    public UserDeposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpNavbar = new javax.swing.JPanel();
        btnUserDashboard = new javax.swing.JButton();
        btnUserDeposit = new javax.swing.JButton();
        btnUserAcc = new javax.swing.JButton();
        btnUserWithdraw = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserTransferFunds = new javax.swing.JButton();
        btnUserBillsPayment = new javax.swing.JButton();
        btnUserCardService = new javax.swing.JButton();
        btnUserSecuritySettings = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jUserDeposit = new javax.swing.JButton();
        jUserEnterAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpNavbar.setBackground(new java.awt.Color(3, 45, 53));

        btnUserDashboard.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDashboard.setText("Dashboard");
        btnUserDashboard.setToolTipText("");
        btnUserDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDashboardActionPerformed(evt);
            }
        });

        btnUserDeposit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserDeposit.setText("Deposit");
        btnUserDeposit.setToolTipText("");
        btnUserDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDepositActionPerformed(evt);
            }
        });

        btnUserAcc.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserAcc.setText("My Account");
        btnUserAcc.setToolTipText("");
        btnUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccActionPerformed(evt);
            }
        });

        btnUserWithdraw.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserWithdraw.setText("Withdraw");
        btnUserWithdraw.setToolTipText("");
        btnUserWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserTransferFunds.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserTransferFunds.setText("Transfer Funds");
        btnUserTransferFunds.setToolTipText("");
        btnUserTransferFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserTransferFundsActionPerformed(evt);
            }
        });

        btnUserBillsPayment.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserBillsPayment.setText("Bills Payment");
        btnUserBillsPayment.setToolTipText("");
        btnUserBillsPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserBillsPaymentActionPerformed(evt);
            }
        });

        btnUserCardService.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserCardService.setText("Card Service");
        btnUserCardService.setToolTipText("");
        btnUserCardService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserCardServiceActionPerformed(evt);
            }
        });

        btnUserSecuritySettings.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnUserSecuritySettings.setText("Security Settings");
        btnUserSecuritySettings.setToolTipText("");
        btnUserSecuritySettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSecuritySettingsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER");

        javax.swing.GroupLayout jpNavbarLayout = new javax.swing.GroupLayout(jpNavbar);
        jpNavbar.setLayout(jpNavbarLayout);
        jpNavbarLayout.setHorizontalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUserWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserTransferFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserBillsPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserCardService, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUserSecuritySettings, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNavbarLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(73, 73, 73)))
        );
        jpNavbarLayout.setVerticalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnUserDashboard)
                .addGap(30, 30, 30)
                .addComponent(btnUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUserDeposit)
                .addGap(30, 30, 30)
                .addComponent(btnUserWithdraw)
                .addGap(28, 28, 28)
                .addComponent(btnUserTransferFunds)
                .addGap(29, 29, 29)
                .addComponent(btnUserBillsPayment)
                .addGap(28, 28, 28)
                .addComponent(btnUserCardService)
                .addGap(27, 27, 27)
                .addComponent(btnUserSecuritySettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
            .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpNavbarLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel5)
                    .addContainerGap(670, Short.MAX_VALUE)))
        );

        add(jpNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 740));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER DASHBOARD");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Deposit Funds");

        jUserDeposit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jUserDeposit.setText("Deposit");

        jUserEnterAmount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jUserEnterAmount.setText("Enter Amount: ₱ [       ]");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Current Balance: ₱");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Bank Reserve: ₱");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jUserDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 314, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserEnterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jUserEnterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jUserDeposit)
                .addGap(59, 59, 59))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 780, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/user.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDashboardActionPerformed

    private void btnUserDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserDepositActionPerformed

    private void btnUserAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserAccActionPerformed

    private void btnUserWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserWithdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserTransferFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserTransferFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserTransferFundsActionPerformed

    private void btnUserBillsPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserBillsPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserBillsPaymentActionPerformed

    private void btnUserCardServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserCardServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserCardServiceActionPerformed

    private void btnUserSecuritySettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSecuritySettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserSecuritySettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUserAcc;
    private javax.swing.JButton btnUserBillsPayment;
    private javax.swing.JButton btnUserCardService;
    private javax.swing.JButton btnUserDashboard;
    private javax.swing.JButton btnUserDeposit;
    private javax.swing.JButton btnUserSecuritySettings;
    private javax.swing.JButton btnUserTransferFunds;
    private javax.swing.JButton btnUserWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jUserDeposit;
    private javax.swing.JTextField jUserEnterAmount;
    private javax.swing.JPanel jpNavbar;
    // End of variables declaration//GEN-END:variables
}
