/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author joshua
 */
public class Update_delete extends javax.swing.JPanel {

    /**
     * Creates new form Update_delete
     */
    public Update_delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpNavbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminDashboard = new javax.swing.JButton();
        btnAdminTransactions = new javax.swing.JButton();
        btnAccManagement = new javax.swing.JButton();
        btnAudits_Reports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        imgBg1 = new javax.swing.JLabel();
        imgBg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Review Application");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 300, 50));

        jPanel2.setBackground(new java.awt.Color(3, 43, 53));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USER ACCOUNT MANAGEMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 550, 60));

        jpNavbar.setBackground(new java.awt.Color(3, 45, 53));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN");

        btnAdminDashboard.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnAdminDashboard.setText("Dashboard");
        btnAdminDashboard.setToolTipText("");
        btnAdminDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDashboardActionPerformed(evt);
            }
        });

        btnAdminTransactions.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnAdminTransactions.setText("Transactions");
        btnAdminTransactions.setToolTipText("");
        btnAdminTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminTransactionsActionPerformed(evt);
            }
        });

        btnAccManagement.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnAccManagement.setText("Manage Accounts");
        btnAccManagement.setToolTipText("");
        btnAccManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccManagementActionPerformed(evt);
            }
        });

        btnAudits_Reports.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnAudits_Reports.setText("Audits & Reports");
        btnAudits_Reports.setToolTipText("");
        btnAudits_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudits_ReportsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpNavbarLayout = new javax.swing.GroupLayout(jpNavbar);
        jpNavbar.setLayout(jpNavbarLayout);
        jpNavbarLayout.setHorizontalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNavbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAudits_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAccManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdminTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpNavbarLayout.setVerticalGroup(
            jpNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNavbarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btnAdminDashboard)
                .addGap(30, 30, 30)
                .addComponent(btnAccManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAdminTransactions)
                .addGap(30, 30, 30)
                .addComponent(btnAudits_Reports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(25, 25, 25))
        );

        add(jpNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 740));

        jPanel1.setAlignmentX(0.9F);
        jPanel1.setAlignmentY(0.9F);

        BtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(568, Short.MAX_VALUE)
                .addComponent(BtnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDelete)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete))
                .addContainerGap(401, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 750, 490));

        searchbar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        searchbar.setText("SEARCH:");
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 630, 30));

        imgBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        imgBg1.setToolTipText("");
        add(imgBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        imgBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        imgBg.setToolTipText("");
        add(imgBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminDashboardActionPerformed

    private void btnAdminTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminTransactionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminTransactionsActionPerformed

    private void btnAccManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccManagementActionPerformed

    private void btnAudits_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudits_ReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAudits_ReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton btnAccManagement;
    private javax.swing.JButton btnAdminDashboard;
    private javax.swing.JButton btnAdminTransactions;
    private javax.swing.JButton btnAudits_Reports;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel imgBg;
    private javax.swing.JLabel imgBg1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpNavbar;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
