/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author Tian
 */
public class Usertrans extends javax.swing.JPanel {

    /**
     * Creates new form usertrans
     */
    public Usertrans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descrption = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userdashboard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userbtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboardbtn = new javax.swing.JButton();
        myaccbtn = new javax.swing.JButton();
        depobtn = new javax.swing.JButton();
        withdrawbtn = new javax.swing.JButton();
        tranferfundbtn = new javax.swing.JButton();
        billsbtn = new javax.swing.JButton();
        cardbtn = new javax.swing.JButton();
        ssbtn = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        fundtrans = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        accno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        amount = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        transferbtn = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descrption.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Description (Optional):");

        javax.swing.GroupLayout descrptionLayout = new javax.swing.GroupLayout(descrption);
        descrption.setLayout(descrptionLayout);
        descrptionLayout.setHorizontalGroup(
            descrptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descrptionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        descrptionLayout.setVerticalGroup(
            descrptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descrptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(descrption, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 710, 60));

        userdashboard.setBackground(new java.awt.Color(3, 43, 53));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("      User Dashboard");

        javax.swing.GroupLayout userdashboardLayout = new javax.swing.GroupLayout(userdashboard);
        userdashboard.setLayout(userdashboardLayout);
        userdashboardLayout.setHorizontalGroup(
            userdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userdashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        userdashboardLayout.setVerticalGroup(
            userdashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userdashboardLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        add(userdashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 350, 60));

        userbtn.setBackground(new java.awt.Color(3, 45, 53));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");

        dashboardbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        dashboardbtn.setText("Dashboard");
        dashboardbtn.setToolTipText("");
        dashboardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardbtnActionPerformed(evt);
            }
        });

        myaccbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        myaccbtn.setText("My Accounts");
        myaccbtn.setToolTipText("");
        myaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myaccbtnActionPerformed(evt);
            }
        });

        depobtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        depobtn.setText("Deposit");
        depobtn.setToolTipText("");
        depobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depobtnActionPerformed(evt);
            }
        });

        withdrawbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        withdrawbtn.setText("Withdraw");
        withdrawbtn.setToolTipText("");
        withdrawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbtnActionPerformed(evt);
            }
        });

        tranferfundbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        tranferfundbtn.setText("Transfer Funds");
        tranferfundbtn.setToolTipText("");
        tranferfundbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranferfundbtnActionPerformed(evt);
            }
        });

        billsbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        billsbtn.setText("Bills payment");
        billsbtn.setToolTipText("");
        billsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsbtnActionPerformed(evt);
            }
        });

        cardbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        cardbtn.setText("Card Services");
        cardbtn.setToolTipText("");
        cardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbtnActionPerformed(evt);
            }
        });

        ssbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        ssbtn.setText("Security Settings");
        ssbtn.setToolTipText("");
        ssbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssbtnActionPerformed(evt);
            }
        });

        btnLogout1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout1.setText("Logout");
        btnLogout1.setToolTipText("");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userbtnLayout = new javax.swing.GroupLayout(userbtn);
        userbtn.setLayout(userbtnLayout);
        userbtnLayout.setHorizontalGroup(
            userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userbtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(withdrawbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tranferfundbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84))
        );
        userbtnLayout.setVerticalGroup(
            userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userbtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(dashboardbtn)
                .addGap(30, 30, 30)
                .addComponent(myaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(depobtn)
                .addGap(30, 30, 30)
                .addComponent(withdrawbtn)
                .addGap(30, 30, 30)
                .addComponent(tranferfundbtn)
                .addGap(30, 30, 30)
                .addComponent(billsbtn)
                .addGap(30, 30, 30)
                .addComponent(cardbtn)
                .addGap(30, 30, 30)
                .addComponent(ssbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnLogout1)
                .addGap(25, 25, 25))
        );

        add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 740));

        fundtrans.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Fund Transfer");

        javax.swing.GroupLayout fundtransLayout = new javax.swing.GroupLayout(fundtrans);
        fundtrans.setLayout(fundtransLayout);
        fundtransLayout.setHorizontalGroup(
            fundtransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundtransLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        fundtransLayout.setVerticalGroup(
            fundtransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundtransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(fundtrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 710, 60));

        accno.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Account Number Receiver:");

        javax.swing.GroupLayout accnoLayout = new javax.swing.GroupLayout(accno);
        accno.setLayout(accnoLayout);
        accnoLayout.setHorizontalGroup(
            accnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accnoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        accnoLayout.setVerticalGroup(
            accnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 710, 60));

        amount.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Amount:");

        javax.swing.GroupLayout amountLayout = new javax.swing.GroupLayout(amount);
        amount.setLayout(amountLayout);
        amountLayout.setHorizontalGroup(
            amountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        amountLayout.setVerticalGroup(
            amountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 710, 60));

        transferbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        transferbtn.setText("Tranfer");
        transferbtn.setToolTipText("");
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });
        add(transferbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, 150, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        bg.setText("jLabel1");
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1060, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardbtnActionPerformed

    private void depobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depobtnActionPerformed

    private void myaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myaccbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myaccbtnActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void tranferfundbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranferfundbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tranferfundbtnActionPerformed

    private void cardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardbtnActionPerformed

    private void billsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsbtnActionPerformed

    private void ssbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssbtnActionPerformed

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accno;
    private javax.swing.JPanel amount;
    private javax.swing.JLabel bg;
    private javax.swing.JButton billsbtn;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton cardbtn;
    private javax.swing.JButton dashboardbtn;
    private javax.swing.JButton depobtn;
    private javax.swing.JPanel descrption;
    private javax.swing.JPanel fundtrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton myaccbtn;
    private javax.swing.JButton ssbtn;
    private javax.swing.JButton tranferfundbtn;
    private javax.swing.JButton transferbtn;
    private javax.swing.JPanel userbtn;
    private javax.swing.JPanel userdashboard;
    private javax.swing.JButton withdrawbtn;
    // End of variables declaration//GEN-END:variables
}
