/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package syntrix.ui;

/**
 *
 * @author Tian
 */
public class Userbills extends javax.swing.JPanel {

    /**
     * Creates new form userbills
     */
    public Userbills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        userbtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dashboardbtn = new javax.swing.JButton();
        myaccbtn = new javax.swing.JButton();
        depobtn = new javax.swing.JButton();
        withdrawbtn = new javax.swing.JButton();
        tranferfundbtn = new javax.swing.JButton();
        billsbtn = new javax.swing.JButton();
        cardbtn = new javax.swing.JButton();
        ssbtn = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        billname = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        paybillbtn1 = new javax.swing.JButton();
        reqpayment = new javax.swing.JButton();
        lines = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 43, 53));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bills Payment");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 430, 60));

        userbtn.setBackground(new java.awt.Color(3, 45, 53));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");

        dashboardbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        dashboardbtn.setText("Dashboard");
        dashboardbtn.setToolTipText("");
        dashboardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardbtnActionPerformed(evt);
            }
        });

        myaccbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        myaccbtn.setText("My Accounts");
        myaccbtn.setToolTipText("");
        myaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myaccbtnActionPerformed(evt);
            }
        });

        depobtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        depobtn.setText("Deposit");
        depobtn.setToolTipText("");
        depobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depobtnActionPerformed(evt);
            }
        });

        withdrawbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        withdrawbtn.setText("Withdraw");
        withdrawbtn.setToolTipText("");
        withdrawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbtnActionPerformed(evt);
            }
        });

        tranferfundbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        tranferfundbtn.setText("Transfer Funds");
        tranferfundbtn.setToolTipText("");
        tranferfundbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranferfundbtnActionPerformed(evt);
            }
        });

        billsbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        billsbtn.setText("Bills payment");
        billsbtn.setToolTipText("");
        billsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsbtnActionPerformed(evt);
            }
        });

        cardbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        cardbtn.setText("Card Services");
        cardbtn.setToolTipText("");
        cardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbtnActionPerformed(evt);
            }
        });

        ssbtn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        ssbtn.setText("Security Settings");
        ssbtn.setToolTipText("");
        ssbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssbtnActionPerformed(evt);
            }
        });

        btnLogout1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnLogout1.setText("Logout");
        btnLogout1.setToolTipText("");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userbtnLayout = new javax.swing.GroupLayout(userbtn);
        userbtn.setLayout(userbtnLayout);
        userbtnLayout.setHorizontalGroup(
            userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userbtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(withdrawbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(myaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(depobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tranferfundbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84))
        );
        userbtnLayout.setVerticalGroup(
            userbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userbtnLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(dashboardbtn)
                .addGap(30, 30, 30)
                .addComponent(myaccbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(depobtn)
                .addGap(30, 30, 30)
                .addComponent(withdrawbtn)
                .addGap(30, 30, 30)
                .addComponent(tranferfundbtn)
                .addGap(30, 30, 30)
                .addComponent(billsbtn)
                .addGap(30, 30, 30)
                .addComponent(cardbtn)
                .addGap(30, 30, 30)
                .addComponent(ssbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnLogout1)
                .addGap(25, 25, 25))
        );

        add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 740));

        jPanel4.setBackground(new java.awt.Color(3, 43, 53));

        billname.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        billname.setForeground(new java.awt.Color(255, 255, 255));
        billname.setText("Bills Name");

        amount.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("Amount");

        duedate.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        duedate.setForeground(new java.awt.Color(255, 255, 255));
        duedate.setText("Due Date");

        status.setFont(new java.awt.Font("Times New Roman", 1, 34)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("Status");

        paybillbtn1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        paybillbtn1.setText("Pay Selected Bill");

        reqpayment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        reqpayment.setText("Manage Recurring Payment");

        lines.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lines.setForeground(new java.awt.Color(255, 255, 255));
        lines.setText("_____________________________________________________________________________");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paybillbtn1)
                .addGap(263, 263, 263))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(billname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reqpayment)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lines, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billname)
                    .addComponent(amount)
                    .addComponent(duedate)
                    .addComponent(status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(lines)
                .addGap(18, 18, 18)
                .addComponent(paybillbtn1)
                .addGap(18, 18, 18)
                .addComponent(reqpayment)
                .addGap(55, 55, 55))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 750, 490));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/syntrix/images/bg.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardbtnActionPerformed

    private void myaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myaccbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myaccbtnActionPerformed

    private void depobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depobtnActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void tranferfundbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranferfundbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tranferfundbtnActionPerformed

    private void billsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsbtnActionPerformed

    private void cardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardbtnActionPerformed

    private void ssbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssbtnActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel billname;
    private javax.swing.JButton billsbtn;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton cardbtn;
    private javax.swing.JButton dashboardbtn;
    private javax.swing.JButton depobtn;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lines;
    private javax.swing.JButton myaccbtn;
    private javax.swing.JButton paybillbtn1;
    private javax.swing.JButton reqpayment;
    private javax.swing.JButton ssbtn;
    private javax.swing.JLabel status;
    private javax.swing.JButton tranferfundbtn;
    private javax.swing.JPanel userbtn;
    private javax.swing.JButton withdrawbtn;
    // End of variables declaration//GEN-END:variables
}
